"""add blacklist

Revision ID: 621deb8c5286
Revises: 9997d2a517be
Create Date: 2022-09-16 16:04:20.007882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621deb8c5286'
down_revision = '9997d2a517be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['users.id'], name=op.f('fk_blacklist_block_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blacklist_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###
