"""users jwt

Revision ID: 9ff0c30c8db8
Revises: cbafa2ef0b56
Create Date: 2022-09-14 11:00:22.334042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ff0c30c8db8'
down_revision = 'cbafa2ef0b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    # ### end Alembic commands ###